# command line: main_cpu.py --weights work_dir/uav/angle/runs-50-13050.pt --config config/uav/test/angle.yaml --phase test --work-dir w_test/uav/angle

base_lr: 0.1
batch_size: 64
config: config/uav/test/angle.yaml
device:
- 0
eval_interval: 5
feeder: feeders.feeder_uav.Feeder
ignore_weights: []
log_interval: 100
lr_decay_rate: 0.1
min_lr: 0.0001
model: model.ctrgcn.Model
model_args:
  graph: graph.uav_human.Graph
  graph_args:
    labeling_mode: spatial
  in_channels: 9
  num_class: 155
  num_person: 2
  num_point: 17
model_saved_name: ''
nesterov: true
num_epoch: 70
num_worker: 0
optimizer: SGD
phase: test
print_log: true
save_epoch: 30
save_interval: 1
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 35
- 55
test_batch_size: 128
test_feeder_args:
  bone: false
  data_path: ../data/angle/test_angle_joint.npy
  debug: false
  label_path: ../data/test_label.npy
  normalization: false
  p_interval:
  - 0.95
  vel: false
  window_size: 120
train_feeder_args:
  bone: false
  data_path: ../data/angle/train_angle_joint.npy
  debug: false
  label_path: ../data/train_label.npy
  normalization: false
  p_interval:
  - 0.9
  random_choose: false
  random_move: false
  random_rot: false
  random_shift: false
  vel: false
  window_size: 120
warm_up_epoch: 5
weight_decay: 0.0004
weights: work_dir/uav/angle/runs-50-13050.pt
work_dir: w_test/uav/angle
